# Generated by Django 4.1.4 on 2022-12-13 11:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('Tutorial_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=90, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover_img', models.ImageField(blank=True, default='images/blog-1.jpg', null=True, upload_to='cover_img')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogstory.category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'db_table': 'tutorial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TutorialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_tutorials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogstory.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment_tuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogstory.tutorial')),
            ],
        ),
    ]
