# Generated by Django 4.1.4 on 2023-07-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogstory', '0002_alter_tutorial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='0.0.0.0', max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='like_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='no_of_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterModelTable(
            name='tutorial',
            table=None,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='blogstory.address'),
        ),
    ]
