# Generated by Django 4.1.4 on 2022-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_big', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_sml', models.CharField(blank=True, max_length=100, null=True)),
                ('url_fst', models.URLField(blank=True, null=True)),
                ('url_snd', models.URLField(blank=True, null=True)),
                ('url_trd', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'db_table': 'home',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'db_table': 'newsletter',
                'managed': True,
            },
        ),
    ]
