# Generated by Django 4.1.4 on 2022-12-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('wahudo', models.CharField(blank=True, max_length=100, null=True)),
                ('aboutyu', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutme')),
            ],
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'managed': True, 'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'managed': True, 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletter'},
        ),
    ]
