# Generated by Django 4.1.4 on 2022-12-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_aboutme_alter_home_options_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'managed': True, 'verbose_name': 'AboutMe', 'verbose_name_plural': 'AboutMe'},
        ),
        migrations.AlterModelTable(
            name='aboutme',
            table='aAboutMe',
        ),
    ]
