# Generated by Django 4.1.4 on 2022-12-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_aboutme_options_alter_aboutme_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutme',
            table='AboutMe',
        ),
    ]
