# Generated by Django 4.1.4 on 2022-12-14 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_aboutme_aboutyu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='aboutyu',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
